services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # User web
      - "3001:3001"  # Shopper web
      - "3002:3002"  # Admin web
      - "4000:4000"  # API
    volumes:
      - .:/app
      # - /app/node_modules
      - yarn_cache:/app/.yarn/cache
    command: sh -c "yarn turbo run dev --parallel --continue"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/otsy
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - NEXT_PUBLIC_API_URL=http://localhost:4000/v1
      - NEXT_PUBLIC_WS_URL=ws://localhost:4000
      # JWT Configuration
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-this-in-production
      # Stripe (for testing)
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret
      # OpenAI (for LLM features)
      - OPENAI_API_KEY=sk-your-openai-api-key
      # AWS S3 (for file storage)
      - AWS_ACCESS_KEY_ID=your-aws-access-key
      - AWS_SECRET_ACCESS_KEY=your-aws-secret-key
      - AWS_REGION=ap-northeast-1
      - AWS_S3_BUCKET=otsy-storage
      # Web Push (for notifications)
      - VAPID_PUBLIC_KEY=your-vapid-public-key
      - VAPID_PRIVATE_KEY=your-vapid-private-key
      - VAPID_SUBJECT=mailto:admin@otsy.app
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    stdin_open: true
    tty: true

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: otsy
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  db_data:
  minio_data:
  node_modules:
  yarn_cache: